[config]

[templates.gtk3]
input_path = './templates/gtk-colors.css'
output_path = '~/.config/gtk-3.0/colors.css'
post_hook = '[[ {{mode}} == "dark" ]] && THEME=adw-gtk3-dark || { [[ {{mode}} == "light" ]] && THEME=adw-gtk3 || exit 1; }; gsettings set org.gnome.desktop.interface gtk-theme "$THEME"'

# [templates.gtk4]
# input_path = './templates/gtk-colors.css'
# output_path = '~/.config/gtk-4.0/colors.css'

[templates.swaync]
input_path = "./templates/swaync-colors.css"
output_path = "~/.config/swaync/colors.css"
post_hook = "swaync-client -rs"

[templates.hyprland]
input_path = './templates/hyprland-colors.conf'
output_path = '~/.config/hypr/colors.conf'

[templates.rofi]
input_path = './templates/rofi-colors.rasi'
output_path = '~/.config/rofi/colors.rasi'

[templates.waybar]
input_path = './templates/waybar-colors.css'
output_path = '~/.config/waybar/colors.css'
post_hook = 'pkill -SIGUSR2 waybar'

[templates.kitty]
input_path = './templates/kitty-colors.conf'
output_path = '~/.config/kitty/themes/Matugen.conf'
post_hook = "kitty +kitten themes --reload-in=all Matugen"
