"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](section1_bg)\
$os\
$username\
[](fg:section1_bg bg:section2_bg)\
$directory\
[](fg:section2_bg bg:section3_bg)\
$git_branch\
$git_status\
[](fg:section3_bg bg:section4_bg)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:section4_bg bg:section5_bg)\
$conda\
$docker_context\
[](fg:section5_bg bg:section6_bg)\
$time\
[ ](fg:section6_bg)\
$cmd_duration\
$line_break\
$character"""

palette = 'matugen'

[os]
disabled = false
style = "bg:section1_bg fg:section1_fg"

[os.symbols]
Windows = ""
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
AOSC = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:section1_bg fg:section1_fg"
style_root = "bg:section1_bg fg:section1_fg"
format = '[ $user]($style)'

[directory]
style = "bg:section2_bg fg:section2_fg"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:section3_bg fg:section3_fg"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:section3_bg fg:section3_fg"
format = '[($all_status$ahead_behind )]($style)'

[nodejs]
symbol = ""
style = "bg:section4_bg fg:section4_fg"
format = '[ $symbol( $version) ]($style)'

[c]
symbol = " "
style = "bg:section4_bg fg:section4_fg"
format = '[ $symbol( $version) ]($style)'

[rust]
symbol = ""
style = "bg:section4_bg fg:section4_fg"
format = '[ $symbol( $version) ]($style)'

[golang]
symbol = ""
style = "bg:section4_bg fg:section4_fg"
format = '[ $symbol( $version) ]($style)'

[php]
symbol = ""
style = "bg:section4_bg fg:section4_fg"
format = '[ $symbol( $version) ]($style)'

[java]
symbol = " "
style = "bg:section4_bg fg:section4_fg"
format = '[ $symbol( $version) ]($style)'

[kotlin]
symbol = ""
style = "bg:section4_bg fg:section4_fg"
format = '[ $symbol( $version) ]($style)'

[haskell]
symbol = ""
style = "bg:section4_bg fg:section4_fg"
format = '[ $symbol( $version) ]($style)'

[python]
symbol = ""
style = "bg:section4_bg fg:section4_fg"
format = '[ $symbol( $version)(\(#$virtualenv\)) ]($style)'

[docker_context]
symbol = ""
style = "bg:section5_bg fg:section5_fg"
format = '[ $symbol( $context) ]($style)'

[conda]
symbol = "  "
style = "bg:section5_bg fg:section5_fg"
format = '[$symbol$environment ]($style)'
ignore_base = false

[time]
disabled = false
time_format = "%R"
style = "bg:section6_bg fg:section6_fg"
format = '[  $time ]($style)'

[line_break]
disabled = true

[character]
disabled = false
success_symbol = '[❯](bold fg:section1_bg)'
error_symbol = '[❯](bold fg:error)'
vimcmd_symbol = '[❮](bold fg:section1_bg)'
vimcmd_replace_one_symbol = '[❮](bold fg:section2_bg)'
vimcmd_replace_symbol = '[❮](bold fg:section2_bg)'
vimcmd_visual_symbol = '[❮](bold fg:section3_bg)'

[cmd_duration]
show_milliseconds = true
format = " in $duration "
style = "fg:section6_bg"
disabled = false
show_notifications = true
min_time_to_notify = 45000

[palettes.matugen]
# 核心装饰色 (Accents)
section1_bg= "{{colors.primary.default.hex}}"
section1_fg= "{{colors.on_primary.default.hex}}"
section2_bg= "{{colors.secondary.default.hex}}"
section2_fg= "{{colors.on_secondary.default.hex}}"
section3_bg= "{{colors.tertiary.default.hex}}" 
section3_fg= "{{colors.on_tertiary.default.hex}}"
section4_bg= "{{colors.primary_container.default.hex}}" 
section4_fg= "{{colors.on_primary_container.default.hex}}"
section5_bg= "{{colors.secondary_container.default.hex}}"
section5_fg= "{{colors.on_secondary_container.default.hex}}"
section6_bg= "{{colors.tertiary_container.default.hex}}"
section6_fg= "{{colors.on_tertiary_container.default.hex}}"
error= "{{colors.error.default.hex}}"
